### ISSUE TITLE
Example 2: comments and possible improvements

### ISSUE THREAD

**Issue by jfaraudo** [sntioudis/papreca#18]
Comments about example 2

**Comment by jfaraudo** [comment]
I like Example 2, adsorption is a classical example in MC.
My only comment is about the trajectory file .xyz geneated by LAMMPS. Apparently the file only contains the particles in the substrate but not the adsorbed atoms. I am showing here typical snapshots that I got by representing the xyz file with VMD.

**Comment by jfaraudo** [comment]
![snapshot](https://github.com/sntioudis/papreca/assets/30062302/c979668c-96e0-41b8-906b-13998c339d71)

**Comment by jfaraudo** [comment]
![vmdscene2](https://github.com/sntioudis/papreca/assets/30062302/63050526-d1b7-4713-b4c3-b611b9da93e5)

**Comment by jfaraudo** [comment]
However the simulation run seems to be executed correctly. This is a typical result for the adsorption

**Comment by jfaraudo** [comment]
![comparison_plot_ra3 0_rd5 0](https://github.com/sntioudis/papreca/assets/30062302/27fd4575-8186-4174-a036-85ae01dd7bfc)

**Comment by jfaraudo** [comment]
I expected to be able to generate visualizations similar to the ones shown in the documentation , with the adsorbed atoms and the substrate. Apparently the dump in LAMMPS indicates to dump everything, so I do not know what may be wrong here.

**Comment by sntioudis** [comment]
> I like Example 2, adsorption is a classical example in MC.
My only comment is about the trajectory file .xyz geneated by LAMMPS. Apparently the file only contains the particles in the substrate but not the adsorbed atoms. I am showing here typical snapshots that I got by representing the xyz file with VMD.

Thank you for your comment. I think this is an issue with VMD. For some reason, VMD cannot handle .xyz file whose number of atoms changes from timestep to timestep. This is exactly the case for this example, since we add/remove (i.e., adsorb/desorb) atoms. OVITO draws all the particles (as depicted in the gif file). You probably faced the same issue in the Phosphates example (i.e., VMD didn't draw the film).

**Comment by sntioudis** [comment]
I reckon I should mention that somewhere in the documentation.

**Comment by jfaraudo** [comment]
Ah OK. But the xyz file contains only atoms of type 1

**Comment by jfaraudo** [comment]
I see, you are right. It is worth mentioning in the documentation. This is a problem in VMD that I always forget, it requires constant number of atoms.

**Comment by sntioudis** [comment]
@jfaraudo I added a comment at the [beginning of the examples section](https://sntioudis.github.io/papreca/md_examples.html). Feel free to close the issue whenever you are satisfied with Example #2.

**Comment by jfaraudo** [comment]
Perfect! I know that a major new release of VMD (2.0) is coming. Maybe the new release is able to cope with variable number of particles. Let us keep an eye on that.

**Comment by jfaraudo** [comment]
Perfect! I know that a major new release of VMD (2.0) is coming. Maybe the new release is able to cope with variable number of particles. Let us keep an eye on that.
